### ISSUE TITLE
Status message not (entirely) visible

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#113]
Hi all,

When I try to upload a file, and it goes wrong, a frame appears with a "status" indication, however, I can't see much more than the word "Status:". So it is not very helpful to find out why my upload fails. Any ideas why no error message is coming through? I'll upload a screen print to show what I mean.

When using Chrome instead of Firefox, I can see a "Status: uploading" message, then Chrome asks for my client cert for authentication; I click cancel because I want to skip towards username/password authentication, and then I get the same: a "Status:" message without any additional message.

To clarify, this issue is not about authentication in dCache View; this is about not seeing helpful status messages.

Kind regards,
Onno
<img width="1392" alt="screen shot 2018-08-23 at 13 06 24" src="https://user-images.githubusercontent.com/781694/44522507-09f48780-a6d7-11e8-89ef-6e92e89724a8.png">

**Comment by femiadeyemi** [comment]
Thanks Onno, I will look into this and get back to you.

**Comment by onnozweers** [comment]
Thanks Femi!

Enjoy your holidays!
