### ISSUE TITLE
Firefox: Loading failed for webcomponents-hi.js

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#157]
Hi,

Last Friday, I updated our test server to the latest 5.1.0-snapshot. Now I'm testing the dCache View interface in Firefox. It remains blank. In the web console I can see this error:

`Loading failed for the <script> with source “https://dolphin12.grid.surfsara.nl:20443/bower_components/webcomponentsjs/webcomponents-hi.js”.`

I've removed content policy and other security headers, but the result is the same. In the Github repo for dCache View, I can see no reference for `webcomponents-hi.js`. Any ideas where this error comes from?

In Chrome, the page loads fine (but in the Chrome console I can't find any reference to webcomponents-hi.js).

Kind regards,
Onno

**Comment by femiadeyemi** [comment]
Thanks for spotting this! I've submitted a fix for this in our review board.
