### ISSUE TITLE
Authentication through dcache-view fails but works through CURL/SWAGGER

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache-view#169]
I am seeing some weirdness with the most recent dcache-view in terms of role authorization.

On my testbed, admin is defined:
```
gplazma.roles.admin-gid=1000
```
dcache.kpwd contains the following for me:
```
mapping "/DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Albert Rossi/CN=UID:arossi" arossi
mapping "arossi@FNAL.GOV" arossi

login admin read-write 0 1000,0 / / /
  /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Albert Rossi/CN=UID:arossi
  arossi@FNAL.GOV


# the following are the user auth records
login arossi read-write 8773 1530,1000,0 / /pnfs/fs/usr/test/arossi /
 /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Albert Rossi/CN=UID:arossi
#  arossi@FNAL.GOV

# the following are the user auth records
passwd arossi ba22a191 read-write 8773 1530,1000,0 / /pnfs/fs/usr/test/arossi
```
The attached is what I see when I assert my admin role.  Everything looks fine.

![dcache-view](https://user-images.githubusercontent.com/3985564/52977229-1c9ffe80-3392-11e9-9a29-ecebc56a0832.jpeg)

BUT.

When I try to disable a pool, I get a 403 back (unauthorized).

I put in a print statement where the frontend isAdmin() check is called on the RequestUser:

```
        if (!RequestUser.isAdmin()) {
            System.out.println(RequestUser.getSubject() + " is not admin.");
            throw new ForbiddenException("Pool command only accessible to admin users.");
        }
```

And this is what I see in the log:

Subject:
       Principal: GidPrincipal[0]
       Principal: /DC=org/DC=cilogon/C=US/O=Fermi National Accelerator Laboratory/OU=People/CN=Albert Rossi/CN=UID:arossi
       Principal: UidPrincipal[8773]
       Principal: Origin[131.225.82.150]
       Principal: EmailAddressPrincipal[arossi@fnal.gov]
       Principal: GidPrincipal[1000]
       Principal: UserNamePrincipal[arossi]
       Principal: GidPrincipal[1530,primary]

...

is not admin.

NOTE:

It works perfectly fine using Swagger-CURL

![curl-swagger](https://user-images.githubusercontent.com/3985564/52977234-232e7600-3392-11e9-8ccd-1a2113acf0eb.jpeg)

Did the internal API for communicating the role to the frontend get changed?
The code in the page has not changed:
```
_sendPoolModeChange(pool, rdonly, strict) {
                this.$.AjaxPatch.url
                    = this.getUrl(`pools/${pool}/usage/mode`, null);
                this.$.AjaxPatch.headers = this.getHeaders();
                this.$.AjaxPatch.body = {
                    "rdonly": rdonly, "strict": strict,
                    "resilience": "true"
                };
                this.$.AjaxPatch.generateRequest();
            }
```

**Comment by paulmillar** [comment]
Hi Al,

What does your `gplazma.conf` file look like?

**Comment by alrossi** [comment]
Here is the gplazma.conf:

```
auth optional voms       
auth optional x509

map      optional   authzdb
session  optional   authzdb
session  required   roles

auth     sufficient  kpwd  "kpwd=/etc/dcache/dcache.kpwd"
map      sufficient  kpwd  "kpwd=/etc/dcache/dcache.kpwd"
session  sufficient  kpwd  "kpwd=/etc/dcache/dcache.kpwd"
```

**Comment by paulmillar** [comment]
It looks like dCacheView knows that you have the `admin` role, but somehow isn't asserting this when trying to disable a pool.

Could you capture the network traffic (e.g., using your web-browser has a developer mode) and verify what information is being sent in the `Authorization` request header.

**Comment by alrossi** [comment]
Femi and I just had a look.  I think Femi understands where the problem might be ...

**Comment by alrossi** [comment]
Still happening with pool movers.  See pull request #177

**Comment by alrossi** [comment]
#192 does not fix it.  With credential in browser, behavior is the same as previously observed (with admin role, cannot view pool movers, billing, etc.)
