### ISSUE TITLE
Poolgroups list: sorting by size works alphabetically, should be numerically

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#170]
Dear dCache devs,

In dCache View, when I sort poolgroups by size, they are sorted alphabetically and not numerically. Also, the unit suffix (TB/GB) is ignored. Tested in 4.2.26.

Screen print included.

<img width="815" alt="schermafbeelding 2019-03-05 om 14 58 41" src="https://user-images.githubusercontent.com/781694/53810957-7985e200-3f58-11e9-9672-52c99ee47555.png">

Cheers,
Onno

**Comment by alrossi** [comment]
Thanks for catching this, Onno.  I have been busy with xrootd third-party proxy delegation, but I will have a look at this soon.  This may be more generalized than just pool groups.

**Comment by alrossi** [comment]
Yes, this is also true for the 'space info' window of the pool group dialog.

**Comment by alrossi** [comment]
Patch:

https://rb.dcache.org/r/11607/

**Comment by femiadeyemi** [comment]
Hi Al, why is this still open?

**Comment by alrossi** [comment]
Thanks, Femi, didn't close automatically and I forgot.

**Comment by onnozweers** [comment]
Thanks Al!
