### ISSUE TITLE
Admin toolbox fails, gets 401 error, API call "authorization:" header empty

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#175]
Dear dCache devs,

On our test server we have 5.1 snapshot. The dCache View there has a broken admin toolbox. Whichever tool I click, I get a 401 error (unauthorized). When I copy the API link that was requested and paste it in a new browser tab, it works fine.

In the log at debug level, I noticed a "Credentials in Authorization header are not-null, but are empty". And indeed, in the Firefox Web Console, I noticed that there was a header: 

`authorization:` 

that was empty. When trying the same in our production dCache (v4.2), there was a nicely filled-in header like this: 

`authorization: Basic xxxxxxxxxxxxxxxxxxxxxxxxxxx`.

And there the tools in the admin toolbox work fine. Otherwise our setup is pretty much the same. I have the admin role in both cases. The main difference is the software version. Could this be a bug?

This issue could be related to #169.

Kind regards
Onno

**Comment by femiadeyemi** [comment]
Hi Onno, 
Thanks for reporting this issue. I will have a look and get back to you.

**Comment by femiadeyemi** [comment]
Hi Onno, we are unable to reproduce this issue. If this issue is related to #169, I've committed a patch to solve it, may you please check if that patch solve this issue. Thank you.

**Comment by onnozweers** [comment]
Hi Femi, I would be very happy to test it, but how? I have a test server with a 5.1 snapshot that I can update. The master snapshot currently has a broken jetty. In which version will your patch be committed?

**Comment by onnozweers** [comment]
I tested with the latest master snapshot:

```
[root@dolphin12 /etc/dcache]# rpm -q dcache
dcache-6.0.0.bb39761-1.noarch
```

And it works now. Thanks!

**Comment by femiadeyemi** [comment]
Thanks for confirming that this is issue is resolve.

**Comment by onnozweers** [comment]
Thank you for fixing it! 😺
