### ISSUE TITLE
Chrome OSX: redirect loop after login

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#183]
Dear dCache devs,

When I log into dCache View (dCache 6.0.0 snapshot) with Chrome 75.0.3770.100 on OSX, I first get a normal window with a directory listing. However, as soon as I go into a subdir or click the "home" button, Chrome gets stuck in a redirect loop, while the login page is shown. I then have to close the browser tab.

In Firefox, I don't see this.

Any idea what could be happening in Chrome?

Cheers,
Onno

**Comment by femiadeyemi** [comment]
Hi Onno, I can seem to reproduce this issue. Is it a publicly available dCache and may you share the link, so that I may have a look?

**Comment by onnozweers** [comment]
Hi Femi, I'd need to open the firewall and create an account for you. I'll get back to you.

**Comment by onnozweers** [comment]
Can you give me a subnet from which that I can permit access?

**Comment by onnozweers** [comment]
It appears the firewall is already open. I've created credentials for you and sent them to your email address.

**Comment by femiadeyemi** [comment]
Thanks for creating the credentials for me. Unfortunately, I'm still not able to reproduce the issue you reported. I logged in and everything worked as expected even I was able to open subdirectory without a running into the redirect loop. 

Although, I noticed a browser login pop-up that is not supposed to be there; this is a bug and I will submit a patch to fix this. Probably this maybe the cause of the loop you're observing. Anyway, I will ping you one I submit the patch.

In the meanwhile, may you please try to clear your browser cache, also use the incognito mode. When you do this, please let me know if this somehow solve the problem. Thanks!

**Comment by onnozweers** [comment]
Hi Femi,

Thanks for checking. I look forward to the patch. I've checked Chrome in Incognito mode, but it behaves the same.

Cheers,
Onno

**Comment by onnozweers** [comment]
Clearing the Chrome cache does not help either.

**Comment by paulmillar** [comment]
@onnozweers, could you try capturing information with the network monitoring of the devtools?

Devtools are opened using Command+Option+J.  This page goes into the networking support in some detail:
    https://developers.google.com/web/tools/chrome-devtools/network/

What I suggest is you first navigate to dCacheView, then enable devtools, selecting "network" tab, select "Preserve log" (near the top) and click the "Clear" symbol (top left, circle with a line through it).

Then attempt to log into dCache, which should trigger the loop.

Right-click on any of the transactions and select `Save all as HAR with content`.  This should tell us exactly what is going wrong.

Cheers,
Paul.

**Comment by onnozweers** [comment]
Hi Paul,

Thanks. I captured a redirect loop in a har file. You can download it from https://surfdrive.surf.nl/files/index.php/s/u3jXKMyWzcIZJGj (share link valid for 1 week).

Cheers,
Onno

**Comment by onnozweers** [comment]
Oh wait. I forgot to click "Preserve log". Will do that and share with the same link.

**Comment by onnozweers** [comment]
When I skip the browser login pop-up by clicking "annuleren" (cancel), and then log in into the grey page, then the redirect loop does not occur.

<img width="938" alt="image" src="https://user-images.githubusercontent.com/781694/60720356-cf7c8d80-9f2a-11e9-8a28-a627aef6ab97.png">

**Comment by femiadeyemi** [comment]
Ah! I see! Now I know what is causing the problem :D, The annoying pop-up suppose not to be there. What is happening is that dCache View (DV) has is own way of handling authentication and the browser pop-up store the credentials in a different path that DV doesn't know it exist.

I have already create a fix for it and it will be release next week.

**Comment by onnozweers** [comment]
Hi Femi,

Thanks for your fix! Would you like me to test it in the master branch? But I have no idea how I can see when `dcache-view` commits are imported in `dcache` branches.

Cheers,
Onno

**Comment by femiadeyemi** [comment]
Hi Onno, I will release the latest version of DV very soon. I will ping you once it's in dCache.

**Comment by femiadeyemi** [comment]
Hi @onnozweers, the latest version of dcache-view is now released.

**Comment by femiadeyemi** [comment]
Hi @onnozweers, any update on this? Did you test it?

**Comment by onnozweers** [comment]
Hi Femi,

Sorry for the delay. I've just tested it on the latest 6.0 snapshot but the bug is still there. The dCache View still asks for the password in a browser login pop-up, and when I log in that way, I still get a redirect loop in Chrome.

Kind regards,
Onno

**Comment by femiadeyemi** [comment]
Hi Onno, 

I just checked your testbed (https://dolphin12.grid.surfsara.nl:20443), you are still using the old version of dcache-view. Please make sure you are using the version 1.5.5. You can check that the master branch of dcache had been updated to this version (see https://github.com/dCache/dcache/blob/f27fc7abe618676afac71ae288ce345306010710/pom.xml#L72).

Best regards,
Femi

**Comment by onnozweers** [comment]
Hi Femi,

Oops, you're completely right, I missed a step during the upgrade. I now upgraded to 6.0.0-SNAPSHOT(f27fc7a). 

Firefox does not show the login popup dialogue anymore, but Chrome (on OSX) still does, and still enters the redirect loop.

Kind regards,
Onno

**Comment by femiadeyemi** [comment]
Good morning Onno, 

Great! I can see that you've upgrade to latest version and at my end everything is working as expected. I tested your testbed with Chrome, FF and Safari and I didn't encounter neither the login pop-up nor the redirect loop.

I think your chrome the browser might have cached the dv pages and scripts and you are still using the old dv. So, I will suggest testing it again using chrome's incognito mode. If this didn't work, then we need to do a video call so that I can see what is going on. 

Please let me know how it goes. Thanks.

Best regards,
Olufemi

**Comment by onnozweers** [comment]
Hi Femi,

Thanks! Indeed it worked normally in incognito mode, so I cleared the browser cache and after that, it worked in normal mode too.

Thanks a lot!
Onno
