### ISSUE TITLE
Adding a share/macaroon works but can't do anything with it

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#189]
Dear dCache people,

I can add macaroons with the "Add a Shared File / Paste the macaroon here" dialogue. And the macaroons I add, appear in the list. But then I can't do anything with them. Can't view, can't view the details, and the other menu options are greyed out.

I've tried in Firefox and Chrome on OSX. I've checked the macaroon for caveats that block access but found none (and dCacheView does not report such).

What could be wrong?

Cheers,
Onno

**Comment by femiadeyemi** [comment]
Hi Onno,

What error messages are you receiving when you try to view the file content or the metadata?

Best regards,
Olufemi

Ps: you might need to switch to chrome's developer mode to see the errors.

**Comment by onnozweers** [comment]
Hi Olufemi,

I now see that this happens when I use a macaroon I created using my script [get-macaroon](https://github.com/sara-nl/GridScripts/blob/master/get-macaroon). These may contain a `cid root:` caveat:

```
cid home:/pnfs/grid.sara.nl/data/users/onno
cid root:/pnfs/grid.sara.nl/data/users/onno/disk-shared/
```

So it appears dCache View handles only `cid path:` statements, not `cid root:` statements.

However, when I try a macaroon that was created with dCache View, I get "directory empty" for a macaroon that points to a directory with two files. For a macaroon that points to a file, I get a 403 error.

Cheers,
Onno

**Comment by femiadeyemi** [comment]
Hi Onno, 

I think this issue is related to the one [here](https://github.com/dCache/dcache/issues/5036). I will probe a bit further to find the cause and fix it as soon as possible. I'll ping once this is done. Thanks.

Best regards,
Olufemi

**Comment by femiadeyemi** [comment]
Hi @onnozweers, 

May you please test if can work with macaroons?

Best regards,
Olufemi

**Comment by onnozweers** [comment]
Hi Olufemi,

I was trying to test, but it seems the latest snapshot breaks WebDAV access from dCacheView. I'll collect some more info and open an issue.

Kind regards,
Onno

**Comment by onnozweers** [comment]
Submitted: #220.

As for this issue, the problem is still the same, I can add a macaroon (created with get-macaroon) but then I can't do anything useful with it. Also, it doesn't have a name in the list. `View Details` doesn't do anything.

![image](https://user-images.githubusercontent.com/781694/73447213-8bd1f100-435e-11ea-8242-8ca4dc417a80.png)

Creating a macaroon by sharing a file or dir from dCacheView doesn't work because of #220.

Kind regards,
Onno

**Comment by femiadeyemi** [comment]
May you please send me a shareable link, let me play with it? Thanks.

**Comment by onnozweers** [comment]
Sure, I've emailed you one that is valid for 8 hours.

**Comment by femiadeyemi** [comment]
I don't know how this macaroon was created but try the following first:
- go to your dcache-view 
- right click on the file you will like to share and click `share` in the context-menu.
- fill the form and share the link with me 
Thanks

**Comment by onnozweers** [comment]
Hi Olufemni,

I'm afraid for that I need #220 to be fixed.

Kind regards,
Onno
