### ISSUE TITLE
QoS: geographic placement hardcoded "DE"?

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#191]
Dear dCache devs,

I've noticed that in dCache View, the geographic placement appears to be hardcoded as `DE`.

![image](https://user-images.githubusercontent.com/781694/62932926-67d71f00-bdc1-11e9-818d-c3a7a131876f.png)

I think the piece of code where this happens is https://github.com/dCache/dcache/blob/master/modules/dcache-frontend/src/main/java/org/dcache/restful/qos/QosManagement.java#L47. I found no option to override this. 

Our users may get confused when they see this; they may think that (part of) our storage falls under German jurisdiction. Are there any plans to make this value admin configurable?

Kind regards,
Onno

**Comment by paulmillar** [comment]
Hi Onno,

Sorry, we started with a hard-coded value, but obviously forgot to make this configurable.  We'll add an extra configuration property to allow you to configure the value.

Cheers,
Paul.

**Comment by onnozweers** [comment]
Tested in 5.2 and it works. Thanks a lot!

```
[root@dcacheview /etc/dcache/layouts]# grep NL *
frontend.geographic-placement = NL
```

<img width="406" alt="image" src="https://user-images.githubusercontent.com/781694/65343639-c029e980-dbd5-11e9-910a-aa281f53a3df.png">
