### ISSUE TITLE
webdav url is set to undefined value and configured endpoint setting is ignored

### ISSUE THREAD

**Issue by ZNikke** [dCache/dcache-view#199]
**Disclaimer** I am no web/js developer, so my solution to this problem might be wrong but the issue nevertheless exists.

While trying to enable dcache-view on Swestore (dCache 5.2.7) we stumbled upon weird errors that turned out to be caused by our frontend.static!dcache-view.endpoints.webdav setting being ignored.

Fumbling around in the debugger and testing around we finally ended up with the following workaround:

```
--- scripts/dv.js.orig  2019-07-09 13:27:44.000000000 +0200
+++ scripts/dv.js       2019-11-07 12:38:47.495958633 +0100
@@ -441,7 +441,7 @@
         } else {
             throw new TypeError("Invalid path: only absolute path is accepted.");
         }
-        const arr = window.CONFIG["webdav"] ?
+        const arr = (window.CONFIG["webdav"] && window.CONFIG["webdav"][operationType] && window.CONFIG["webdav"][operationType].length > 0) ?
             window.CONFIG["webdav"][operationType] : window.CONFIG["dcache-view.endpoints.webdav"] ?
                 [window.CONFIG["dcache-view.endpoints.webdav"]] :
                 [`${window.location.protocol}//${window.location.hostname}:2880`];
@@ -728,4 +728,4 @@
     window.addEventListener('dv-namespace-close-files-viewer',(e)=>{
         app.$.filesViewerOverlay.close();
     });
-})(document);
\ No newline at end of file
+})(document);
```

```
--- elements/elements.html.orig 2019-07-09 13:29:04.000000000 +0200
+++ elements/elements.html      2019-11-07 12:38:46.479944784 +0100
@@ -11178,7 +11178,7 @@
                 } else {
                     throw new TypeError("Invalid path: only absolute path is accepted.");
                 }
-                const arr = window.CONFIG["webdav"] ?
+                const arr = (window.CONFIG["webdav"] && window.CONFIG["webdav"][operationType] && window.CONFIG["webdav"][operationType].length > 0) ?
                     window.CONFIG["webdav"][operationType] : window.CONFIG["dcache-view.endpoints.webdav"] ?
                         [window.CONFIG["dcache-view.endpoints.webdav"]] :
                         [`${window.location.protocol}//${window.location.hostname}:2880`];
@@ -77588,4 +77588,4 @@
         }
     }
     window.customElements.define(QosBackendInformation.is, QosBackendInformation);
-</script></div>
\ No newline at end of file
+</script></div>
```

From what we can surmise, window.CONFIG["webdav"] is filled by some stray items so the original check is insufficient. I just expanded the check to ensure that the array existed and was non-empty, which enabled the code to actually use our configured endpoint name instead of the non-helpful URL "undefined" ...

This brought us from the state "no file operation works when logged in" to "things seems to work when logged in with username/password auth", which is a step forward for us. It's strange that the original code seems to work for others, so we likely have config errors somewhere still, but this improved check shouldn't damage the cases that previously worked...

**Comment by alrossi** [comment]
Assigning to Olufemi.

**Comment by ZNikke** [comment]
This particular code seems to have been modified multiple times since this issue was reported, most recently in 42112ca2. Since we haven't had to reapply our workaround lets just assume this issue is solved.
