### ISSUE TITLE
Request: Display unix permissions on a file or directory

### ISSUE THREAD

**Issue by nsc-jens** [dCache/dcache-view#202]
We are trying to set up dcache-view as a general file access method for Swestore. There are a few things in the web GUI that we miss.

In the interface, show the unix permissions on a file or directory.

Example:
```
Type   Name       Permissions   Creation time           File location   Size
ICON   beer.jpg   -rwxrwxr-x    11/7/2019, 3:29:24 PM   Disk            86.1 KB
ICON   food       drwxrwsr-x    11/7/2019, 3:29:32 PM   Disk            -
```

**Comment by paulmillar** [comment]
Hi Jens,

Although quite a few people (myself included) are very familiar with this representation of permissions, I'm wondering if this is the best way of conveying this information.

Since it should be rather easy to implement this, I would imagine adding a UNIX-ls-like field would be added first; however, perhaps we can also provide this information in a more graphic format, too.

**Comment by nsc-jens** [comment]
Yes. Execute permissions is rather unimportant (unless you have NFS). And user "rwx" is also kind of uninteresting. File or directory) is kind of displayed using the Type column. This leaves rw for group or other which is little enough to perhaps display graphically.

In the best of worlds we could perhaps have booth and user configurable. As a start I'd like to see the regular unix permissions (which would also show the setuid, setgid and sticky bits). This gives a kind of familiarity to many users.

**Comment by paulmillar** [comment]
> Execute permissions is rather unimportant

As an aside: the `x` bit controls whether you are allowed to reference a directory contents (or "cd into" the directory), which is distinct from being able to list a directory (the `r` bit).

But, in general, I think we agree that adding this should be (relatively) easy to do and would help people, especially those familiar with UNIX/Linux.

**Comment by nsc-jens** [comment]
Ah, yes. I forgot about the x-bit on directories.

**Comment by ZNikke** [comment]
Added a pull request with the basic addition of the ls-style mode bits.

If we add more stuff in the file listing like https://github.com/dCache/dcache-view/issues/201 suggests an on/off-toggle might be a good idea. I'm thinking something styled similar to the raw/formatted toggle in the view details dialog, and it having a similiar effect as the `-l` option to ls, ie switch of most details (perhaps only show file/dir name and size vs everything).
