### ISSUE TITLE
dcache-view access issues

### ISSUE THREAD

**Issue by SarwarAleem** [dCache/dcache-view#211]
1- If log in using OIDC and try to upload a file. The file is not uploaded and It shows an error which is not helpful to track the problem.

2- Logging out and logging in doesn't solve the issue. It mean the dcache-view is using expired access token. 
Screenshot is attached where the user is log in but dcache-view is in fetching data mode. 

![07012020](https://user-images.githubusercontent.com/59685756/72053651-c1d40600-32c7-11ea-9df7-61e78d7fa275.png)
![08012020](https://user-images.githubusercontent.com/59685756/72053653-c26c9c80-32c7-11ea-94d0-2e18c17bc18a.png)

**Comment by femiadeyemi** [comment]
Hi @SarwarAleem, can I close this? Since we've been able to traced this problem to dcache not dv

**Comment by SarwarAleem** [comment]
Yes Please
