### ISSUE TITLE
Missing details when file is uploaded

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache-view#225]
In dCache v6.0.8, when uploading a file using dCacheView, the directory listing is updated so it includes the newly created file.  However, dCacheView does not know anything about the file: right-clicking the file and selecting "View details" shows no information.  The raw data shows an empty JSON Object.

A consequence is that uploading an HDF5 file does not show the HDF5 icon, The "File location" field is "unavailable".

Relisting the current directory shows all expected values.

**Comment by femiadeyemi** [comment]
Hi Paul, I couldn't reproduce your error (- followed the procedure you described above) in either my system-test or on prometheus. Does this happen to only HDF5 or just any file?

**Comment by paulmillar** [comment]
I was testing this on dcache-demo.desy.de.  This is (currently) running dCache v6.0.8, while prometheus and system-test are from master branch.  That might explain the differences.

The missing icon seems to be for HDF5.  When I uploaded a .jpg file dCacheView used the correct icon.  However, the metadata was still missing.

**After successfully uploading HDF5 file**
![upload-wrong-1](https://user-images.githubusercontent.com/533081/73838576-4442dd80-4814-11ea-83ea-0da91989a186.png)

**Viewing missing metadata**
![upload-wrong-3](https://user-images.githubusercontent.com/533081/73838630-64729c80-4814-11ea-905b-fa5f56b1771a.png)

**After refreshing the directory list**
![upload-wrong-2](https://user-images.githubusercontent.com/533081/73838599-51f86300-4814-11ea-8be2-9a0ca3adde8e.png)

**Uploading an image**
![upload-wrong-4](https://user-images.githubusercontent.com/533081/73838658-794f3000-4814-11ea-9d4e-ff1d840045e0.png)

Note: the icon is correct, but the file location is missing.

**Viewing image's missing metadata**
![upload-wrong-5](https://user-images.githubusercontent.com/533081/73838711-9a178580-4814-11ea-993e-d9d2f8e344ba.png)

**Comment by femiadeyemi** [comment]
Fix posted, see: https://rb.dcache.org/r/12203/
