### ISSUE TITLE
Support direct sharing of files

### ISSUE THREAD

**Issue by paulmillar** [dCache/dcache-view#246]
When the user selects sharing a file, the returned URL is a link pointed back to dCacheView.

While this works, it is also (sometimes) helpful to provide direct access to the file.  This is to allow people to download the file directly (e.g., using curl), without using dCacheView.

In other words, the URL should point to the WebDAV door with the macaroon embedded.

So, if the WebDAV link for a file is:

    https://webdav.example.org/path/to/file

and the macaroon is `MACAROON`

then the share dialogue box should offer the user the possibility of getting a direct link to the file.  For the above example, the URL would be:

    https://webdav.example.org/path/to/file?Authz=MACAROON

**Comment by ZNikke** [comment]
As I understand it, the link pointing back to dCacheView doesn't work when sharing a file to a user without an account (ie, the common reason for using the share feature).

From a user perspective, they would prefer a share link that always work for accessing the file, so as a server admin I would actually like to be able to configure the default behavior here.

I think the same applies to shared directories, users would prefer to be able to cut&paste the shared URL directly into browsers but also rclone for example.

**Comment by paulmillar** [comment]
@ZNikke , The share URL (that pointing back to dCacheView) should work for anyone, irrespective of whether or not they have an account.  It is a bug if the link requires the user to authenticate.

This issue is about something else.

The generated URL assumes that the user is using a web-browser.  Accessing the URL (technically issuing an HTTP GET request) returns a minimal web-page (i.e., HTML) that includes links to download a JavaScript client (i.e., dCacheView).  dCacheView (which runs in the web-browser) then offers the user the chance to explore the shared data and to download the files.

Therefore, if you put the URL in a web-browser, everything should work fine.

However, if the person generating the share might only share a single file.  The person receiving the URL might just want to download that file's data.  The recipient doesn't want to open up a web-browser to do this: they want direct access to the file's data.

This is already technically possible, but it is currently not offered as an option by dCache View.  Instead, the provided URL must be placed in a web-browser.

**Comment by ZNikke** [comment]
Yeah, I'm sorry for mixing the issues (got a little carried away).

I agree that the user probably just want to download the shared data, for example using tools like `wget`, `curl` or `rclone`. The latter is probably the preferred tool to use with a directory share, especially since dCache View doesn't provide multi-file download yet...

**Comment by paulmillar** [comment]
Exactly.

If the user wants to use `wget` to "just download the data" then this currently doesn't work with dCacheView, although dCache itself would support this.

Multi-file download would also work if the client uses WebDAV (which `rclone` does).  Incidentally, SurfSARA do this already; sharing access with macaroons and rclone.  They just don't use dCacheView to generate the macaroon.

Multi-file download for `wget` or `curl` would likely mean the user downloads an archive file (e.g., a `.zip` file) containing the different files.  This is do-able, even building the archive dynamically and streaming it to the client, but just isn't a high enough priority at the moment.

Supporting multi-file download in dCache View would also be useful; however, that, too, would be a different issue.

**Comment by ZNikke** [comment]
I'll likely have a go at adding a direct download link to that dialog, I'm poking at various low hanging fruits anyway to get this in shape to be usable for us (ie. for our users).

**Comment by paulmillar** [comment]
That sounds good.

If your touching that part of the code-base, you might like to also add a button for working with the share as an `rclone` configuration (a share might be an invitation for collaborative work, not just downloading files).  Thanks to the work from SurfSARA, rclone's WebDAV support [can work with a macaroon](https://rclone.org/webdav/#dcache), so this should be easy to do.

**Comment by ZNikke** [comment]
I'll look into it. I'm in no way a web developer, so the most challenging stuff seems to be getting the layout stuff show things in a sane way. Digging into it I find other things like the QR code is being generated in one resolution and then scaled, which is not ideal.
We'll se what I manage to solve and what results in more issues filed...

**Comment by ZNikke** [comment]
Added a pull request with my work. The content should be OK, but layout-wise it's about as far as I get with my limited know-how of the framework used and HTML/CSS details. It works as-is, but I suspect that with odd browser window sizes or phones/tablets things might get weird.
