### ISSUE TITLE
Admin: active mover kill

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache-view#88]
This is mainly a problem of bad error message.

500 is returned when the mover is no longer there.  Should be more informative.

This is also a back-end issue.

**Comment by alrossi** [comment]
There is, however, an issue with interaction between filter and select here as well.   When the filter is cancelled, all selections are lost.

**Comment by alrossi** [comment]
Upon further thought/investigation, the behavior here is necessary, from the standpoint of lazy loading.   When the filter changes, everything is reloaded lazily, so maintaining state as to what is checked and what is not would lead to potential inconsistencies.   This is unlike the built-in interaction, where the dataset remains stable in memory in the browser.   So no changes are necessary here.

The only thing we need to do is remove the entry if we get a 500 response.

**Comment by femiadeyemi** [comment]
Al, isn't this fix?

**Comment by alrossi** [comment]
Most of this was fixed on the RESTful side, I believe.  I am closing the issue.

**Comment by alrossi** [comment]
Yes, thanks Femi.  I closed the issue.


________________________________________________
Albert L. Rossi
Application Developer & Systems Analyst III
Scientific Computing Division, Data Movement Development
FCC 229A
Mail Station 369 (FCC 2W)
Fermi National Accelerator Laboratory
Batavia, IL 60510
(630) 840-3023


________________________________
