### ISSUE TITLE
turn off refresh if not authenticated

### ISSUE THREAD

**Issue by alrossi** [dCache/dcache-view#91]
when receive an error, stop the refresh

**Comment by alrossi** [comment]
This is actually a larger issue.  We need to guarantee that refresh is cancelled when we switch from one admin tab to the next, via routing event.

**Comment by alrossi** [comment]
Changed your mind, I see :-)

**Comment by femiadeyemi** [comment]
Sorry @alrossi, I didn't notice that you've submitted the patch that solve the closed issue. Please ignore me.
