### ISSUE TITLE
Request: support for macaroons (share links)

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#97]
Hi,

We would very much like support for macaroons (share links) in dCache View! Now, when our users want to share data, we have to do all sorts of things (create accounts, set ACLs) to make it possible. It would be awesome if, like in ownCloud, users could easily obtain a share link themselves that they can hand out to someone they need to share data with.

We can get share links with scripts in a shell, but in dCache View it would be much more user friendly. 

Thanks!
Onno

**Comment by femiadeyemi** [comment]
Hi Onno,

There is currently a patch in our review board (https://rb.dcache.org/r/10953/) addressing this issue. Hence, this will be part of dcache-view v1.5 which will be release soon. I will personally ping you once this is available.

/FM

**Comment by onnozweers** [comment]
Thanks Femi!
