### ISSUE TITLE
Admin role switch keeps flipping on

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#98]
Hi,

I made myself member of the admin group, and when I click the "your profile" icon, I can see the switch behind the "admin" role is switched on. When I click the switch, it appears to be switched off and turns from green to red. However, when I click the "your profile" icon again, the role switch is switched back to the on position and it is green again. Is this a bug? I'm testing dCache 4.3.

Kind regards,
Onno

**Comment by paulmillar** [comment]
Yeah, sounds like a bug.

Which version is that, again?  I'm not sure we have a dCache v4.3

**Comment by onnozweers** [comment]
It's this week's 4.3-snapshot, built from source.

**Comment by paulmillar** [comment]
OK, that's keen!
