### ISSUE TITLE
Avatar icon does not appear, instead "busy" icon

### ISSUE THREAD

**Issue by onnozweers** [dCache/dcache-view#99]
Hi,

Using Firefox, in the "your profile" page, it seems there is a permanent "busy loading" icon where I would expect an avatar image. See screen photo:

![img_e3813](https://user-images.githubusercontent.com/781694/41772488-23327c46-7619-11e8-9d8f-de80d8cd36fa.JPG)

When using Chrome, it works as expected: I can see an avatar icon.

Kind regards,
Onno

**Comment by onnozweers** [comment]
Firefox for OSX 60.0.1 64 bit
Chrome for OSX Version 67.0.3396.87 (Official Build) (64-bit)

**Comment by femiadeyemi** [comment]
Hi Onno, I can't seem to reproduce this issue. Do you have gravatar associated with your username?

**Comment by paulmillar** [comment]
Does your browser send an X.509 certificate?  IIRC, gravator are linked to email addresses, and we only get your email address through OpenID-Connect or your X.509 EEC.  (Even if you authenticate with username and password authentication, if the browser sends a certificate then gPlazma will see it and extract the DN and email address.)

**Comment by onnozweers** [comment]
A certificate may indeed have to do with it.

When in Firefox I open a new private window, and I go to the dCache View, it asks for my user certificate. If I click OK to submit my cert, I am logged in and I can read my files and not someone else's files. However, I don't see a "your profile" button, and I do see a "log in" button. So it appears that on one level I am logged in, and on another I am not logged in.

The I click the "log in" button and I log in with my username/password. Then I see the "your profile" button and I can see the "logged in as" info in the upper right corner. Then, if I click "your profile", I see the busy icon where the avatar icon is expected.

If I start from scratch in another private window, and refuse to present my user certificate, and log in with username/password, and then go to "your profile", I see a (default) avatar icon.

In Chrome I don't have my certificate, that is probably why I see a default avatar there, and no busy icon.
